import { Meteor } from 'meteor/meteor';
import { Accounts } from 'meteor/accounts-base';
import { Mongo } from 'meteor/mongo';
import SimpleSchema from 'simpl-schema';

export const Branches = new Mongo.Collection('branches');

Branches.schema = new SimpleSchema({
    // _id: {type: String}, //I'm sure this is not needed as we will never validate an id as it is generated by the server -Arian
    name: {type: String},
    manager: {type: String},
    staff: [{type: Object}],
    "staff.name": {
        type: String
    },
    "staff.id": {
        type: String
    },
    "staff.role": {
        type: String
    },
    phone: {type: Number},
    address: {type: Object},
    "address.unitNo": {
        type: String              //Can have unit numbers 3A 2B etc
    },
    "address.street": {
        type: String
    },
    "address.streetNumber": {
        type: String              //Using string as we might expect street numbers with special characters (e.g 1-13 or 1/34)
    },
    "address.city": {
        type: String
    },
    "address.state": {
        type: String
    },
    "address.postCode": {
        type: Number              //Australian postal codes are always numbers
    },
    createdAt: {type: Date},
});

if (Meteor.isServer) {
    Meteor.methods({
        'branches.insert': function(bName, bManager, bPhone, bAddress) {
            console.log("attempting to add branch");
            if (this.userId) {
                if (Roles.userIsInRole(this.userId,'admin')) {
                    Branches.insert({
                        name: bName,
                        manager: bManager,
                        phone: bPhone,
                        address: bAddress,
                        staff: [{}]
                    });
                } else {
                    throw new Meteor.Error('Insufficient permissions', "Must be of role 'ADMIN'");
                }
            } else {
                throw new Meteor.Error('Not logged in', "Must be logged in");
            }
        },
        'branches.addStaff': function(staffEmail, branchID, staffRole) {
            if (!this.userId) {
                throw new Meteor.Error('Not logged in', "Must be logged in");
            } else if (!Roles.userIsInRole(this.userId,'admin')) {
                throw new Meteor.Error('Insufficient permissions', "Must be of role 'ADMIN'");
            }
            if (Branches.find({_id: branchID}).count() === 0) {
                throw new Meteor.Error('Branch not found!', "Branch could not be found");
            }

            //console.log({staffEmail, branchID, staffRole});
            const staffUser = Accounts.findUserByEmail(staffEmail);

            if (staffUser) {
                if (staffUser.assignedBranch) {
                    if (staffUser.assignedBranch !== '') {
                        throw new Meteor.Error('Logical Inconsistency', "Staff is already assigned a branch, cannot multiple times.");
                    }
                }

                // We will add the branch ID to the user object after a couple more checks in the code below.
                // The error handling above will make sure that we don't run anything else unless we know the staffID

                const staffEntry = {
                    name: staffUser.profile.name,
                    id: staffUser._id,
                    role: staffRole
                }

                // Branch update must occur first just incase the branch was not found.
                // This will make sure we do not promote a user to staff and assign it a branch
                // that does not exist in the database.
                Branches.update({_id: branchID}, {
                    $push: {
                        "staff": staffEntry
                    }
                }, {multi: false} ,function(error, affectedDocs) {
                    if(error) {
                        throw error;
                    }
                });

                // Update the user record to reflect it is not connected to a branch.
                // After this, the user is essentially a staff member and is added to the staff role group.
                Meteor.users.update({_id: staffUser._id}, {
                    $set: {assignedBranch: branchID}
                }, {multi: false}, function(error, affectedDocs) {
                    if(error) {
                        throw new Meteor.Error('Database error', "Could not update user record");
                    } else if(affectedDocs > 0) {
                        Roles.addUsersToRoles(staffUser._id, 'staff');
                    }
                });

            } else {
                throw new Meteor.Error('User not found', "Could not find user of email " + staffEmail);
            }
        }
    });
}

