import { Meteor } from 'meteor/meteor';
import { Accounts } from 'meteor/accounts-base';
import { Mongo } from 'meteor/mongo';
import SimpleSchema from 'simpl-schema';

export const Branches = new Mongo.Collection('branches');

Branches.schema = new SimpleSchema({
    // _id: {type: String}, //I'm sure this is not needed as we will never validate an id as it is generated by the server -Arian
    manager: {type: String},
    staff: {type: Object},
    "staff.name": {
        type: String
    },
    "staff.id": {
        type: String
    },
    name: {type: String},
    phone: {type: Number},
    address: {type: Object},
    "address.unitNo": {
        type: String              //Can have unit numbers 3A 2B etc
    },
    "address.street": {
        type: String
    },
    "address.streetNumber": {
        type: String              //Using string as we might expect street numbers with special characters (e.g 1-13 or 1/34)
    },
    "address.city": {
        type: String
    },
    "address.state": {
        type: String
    },
    "address.postCode": {
        type: Number              //Australian postal codes are always numbers
    },
    createdAt: {type: Date},
});

Meteor.methods({
    'branches.insert': function(bName, bManager, bPhone, bAddress) {
        console.log("attempting to add branch");
        console.log(bManager);
        console.log(Accounts.findUserByUsername(bManager));

    }
});

